defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password:

production:
  <<: *defaults

test:
  database: demoapp3_test
  <<: *defaults

development:
  database: demoapp3_development
  <<: *defaults